//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniKey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UniKey.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,¬&gt;ˌ;:¬&gt;ː;&apos;¬&gt;ˈ;a.¬&gt;ȧ;A.¬&gt;Ȧ;aa¬&gt;ꜳ;AA¬&gt;Ꜳ;ab¬&gt;ă;Ab¬&gt;Ă;ac¬&gt;â;Ac¬&gt;Â;ad¬&gt;ä;Ad¬&gt;Ä;ae¬&gt;æ;AE¬&gt;Æ;ag¬&gt;à;Ag¬&gt;À;ao¬&gt;ꜵ;AO¬&gt;Ꜵ;au¬&gt;ꜷ;AU¬&gt;Ꜷ;av¬&gt;ꜹ;AV¬&gt;Ꜹ;ay¬&gt;ꜽ;AY¬&gt;Ꜽ;b.¬&gt;ḃ;B.¬&gt;Ḃ;b_¬&gt;ḇ;B_¬&gt;Ḇ;bt¬&gt;ƃ;Bt¬&gt;Ƃ;c.¬&gt;ċ;C.¬&gt;Ċ;cc¬&gt;ĉ;Cc¬&gt;Ĉ;d.¬&gt;ḋ;D.¬&gt;Ḋ;d_¬&gt;ḏ;D_¬&gt;Ḏ;db¬&gt;ȸ;dt¬&gt;ƌ;Dt¬&gt;Ƌ;dz¬&gt;ǳ;Dz¬&gt;ǲ;DZ¬&gt;Ǳ;e.¬&gt;ė;E.¬&gt;Ė;eb¬&gt;ĕ;Eb¬&gt;Ĕ;ec¬&gt;ê;Ec¬&gt;Ê;ed¬&gt;ë;Ed¬&gt;Ë;eg¬&gt;è;Eg¬&gt;È;et¬&gt;ꝫ;ET¬&gt;Ꝫ;f.¬&gt;ḟ;F.¬&gt;Ḟ;ff¬&gt;ﬀ;fi¬&gt;ﬁ;fl¬&gt;ﬂ;g.¬&gt;ġ;G.¬&gt;Ġ;gb¬&gt;ğ;Gb¬&gt;Ğ;gc¬&gt;ĝ;Gc¬&gt;Ĝ;gs¬&gt;ʔ;h.¬&gt;ḣ;H.¬&gt;Ḣ;h_¬&gt;ẖ;hc¬&gt;ĥ;Hc¬&gt;Ĥ;hd¬&gt;ḧ;Hd¬&gt;Ḧ;hv¬&gt;ƕ;I.¬&gt;İ;ib¬&gt;ĭ;Ib¬&gt;Ĭ;ic¬&gt;î;Ic¬&gt;Î;id¬&gt;ï;Id¬&gt;Ï;ig¬&gt;ì;Ig¬&gt;Ì [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000;&lt;control&gt;;Cc;0;BN;;;;;N;NULL;;;;
        ///0001;&lt;control&gt;;Cc;0;BN;;;;;N;START OF HEADING;;;;
        ///0002;&lt;control&gt;;Cc;0;BN;;;;;N;START OF TEXT;;;;
        ///0003;&lt;control&gt;;Cc;0;BN;;;;;N;END OF TEXT;;;;
        ///0004;&lt;control&gt;;Cc;0;BN;;;;;N;END OF TRANSMISSION;;;;
        ///0005;&lt;control&gt;;Cc;0;BN;;;;;N;ENQUIRY;;;;
        ///0006;&lt;control&gt;;Cc;0;BN;;;;;N;ACKNOWLEDGE;;;;
        ///0007;&lt;control&gt;;Cc;0;BN;;;;;N;BELL;;;;
        ///0008;&lt;control&gt;;Cc;0;BN;;;;;N;BACKSPACE;;;;
        ///0009;&lt;control&gt;;Cc;0;S;;;;;N;CHARACTER TABULATION;;;;
        ///000A;&lt;control&gt;;Cc;0;B;;;;;N;LINE FEED (LF);;;;
        ///000B;&lt;contro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnicodeData {
            get {
                return ResourceManager.GetString("UnicodeData", resourceCulture);
            }
        }
    }
}
