using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace UniKey
{
    static class KeyToChar
    {
        internal static Dictionary<Keys, char> NoShift = new Dictionary<Keys, char>
        {
            { Keys.Oemtilde, '`' },
            { Keys.D1, '1' },
            { Keys.D2, '2' },
            { Keys.D3, '3' },
            { Keys.D4, '4' },
            { Keys.D5, '5' },
            { Keys.D6, '6' },
            { Keys.D7, '7' },
            { Keys.D8, '8' },
            { Keys.D9, '9' },
            { Keys.D0, '0' },
            { Keys.OemMinus, '-' },
            { Keys.Oemplus, '=' },
            { Keys.Q, 'q' },
            { Keys.W, 'w' },
            { Keys.E, 'e' },
            { Keys.R, 'r' },
            { Keys.T, 't' },
            { Keys.Y, 'y' },
            { Keys.U, 'u' },
            { Keys.I, 'i' },
            { Keys.O, 'o' },
            { Keys.P, 'p' },
            { Keys.OemOpenBrackets, '[' },
            { Keys.Oem6, ']' },
            { Keys.A, 'a' },
            { Keys.S, 's' },
            { Keys.D, 'd' },
            { Keys.F, 'f' },
            { Keys.G, 'g' },
            { Keys.H, 'h' },
            { Keys.J, 'j' },
            { Keys.K, 'k' },
            { Keys.L, 'l' },
            { Keys.Oem1, ';' },
            { Keys.Oem7, '\'' },
            { Keys.Oem5, '\\' },
            { Keys.OemBackslash, '¬' },
            { Keys.Z, 'z' },
            { Keys.X, 'x' },
            { Keys.C, 'c' },
            { Keys.V, 'v' },
            { Keys.B, 'b' },
            { Keys.N, 'n' },
            { Keys.M, 'm' },
            { Keys.Oemcomma, ',' },
            { Keys.OemPeriod, '.' },
            { Keys.OemQuestion, '/' },
            { Keys.Space, ' ' }
        };

        internal static Dictionary<Keys, char> Shift = new Dictionary<Keys, char>
        {
            { Keys.Oemtilde, '~' },
            { Keys.D1, '!' },
            { Keys.D2, '@' },
            { Keys.D3, '#' },
            { Keys.D4, '$' },
            { Keys.D5, '%' },
            { Keys.D6, '^' },
            { Keys.D7, '&' },
            { Keys.D8, '*' },
            { Keys.D9, '(' },
            { Keys.D0, ')' },
            { Keys.OemMinus, '_' },
            { Keys.Oemplus, '+' },
            { Keys.Q, 'Q' },
            { Keys.W, 'W' },
            { Keys.E, 'E' },
            { Keys.R, 'R' },
            { Keys.T, 'T' },
            { Keys.Y, 'Y' },
            { Keys.U, 'U' },
            { Keys.I, 'I' },
            { Keys.O, 'O' },
            { Keys.P, 'P' },
            { Keys.OemOpenBrackets, '{' },
            { Keys.Oem6, '}' },
            { Keys.A, 'A' },
            { Keys.S, 'S' },
            { Keys.D, 'D' },
            { Keys.F, 'F' },
            { Keys.G, 'G' },
            { Keys.H, 'H' },
            { Keys.J, 'J' },
            { Keys.K, 'K' },
            { Keys.L, 'L' },
            { Keys.Oem1, ':' },
            { Keys.Oem7, '"' },
            { Keys.Oem5, '|' },
            { Keys.OemBackslash, '¦' },
            { Keys.Z, 'Z' },
            { Keys.X, 'X' },
            { Keys.C, 'C' },
            { Keys.V, 'V' },
            { Keys.B, 'B' },
            { Keys.N, 'N' },
            { Keys.M, 'M' },
            { Keys.Oemcomma, '<' },
            { Keys.OemPeriod, '>' },
            { Keys.OemQuestion, '?' },
            { Keys.Space, ' ' }
        };
    }
}
